repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        files: backend
        exclude: backend/alembic
        args: ["--check"]
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.0'
    hooks:
    -   id: flake8
        exclude: backend/alembic
        args: ["backend/", "--config", "backend/setup.cfg"]
