version: "3.3"
# version: "3.9" # local
services:
  db:
    image: postgres:alpine
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qwork

  backend:
    image: qwork-backend
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/qwork
    command: bash -c "./scripts/run.sh"
    depends_on:
      - db

  frontend:
    image: qwork-frontend
    build:
      context: ./frontend
    ports:
      # - "8000:80" # local
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    

volumes:
  caddy_data:
  caddy_config:
  postgres-db:
