global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dramatiq'
    # scrape_interval: 5s
    static_configs:
      - targets: ['dramatiq:9191']
  
  - job_name: 'backend'
    # scrape_interval: 5s
    static_configs:
      - targets: ['backend:8000']
