"""Added created_at and updated_at meta to run model

Revision ID: 2a846ee9cec9
Revises: 5d6bd8ded9da
Create Date: 2022-05-05 21:48:21.111819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a846ee9cec9'
down_revision = '5d6bd8ded9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('runs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'updated_at')
    op.drop_column('runs', 'created_at')
    # ### end Alembic commands ###
