"""Renamed Runs table

Revision ID: 5d6bd8ded9da
Revises: 83faaee45526
Create Date: 2022-04-11 21:39:05.033442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d6bd8ded9da'
down_revision = '83faaee45526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_corresponding', sa.Boolean(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('systole_pressure', sa.Integer(), nullable=True),
    sa.Column('diastole_pressure', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_id'), 'runs', ['id'], unique=False)
    op.drop_index('ix_text_process_result_id', table_name='text_process_result')
    op.drop_table('text_process_result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_process_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_corresponding', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('temperature', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('systole_pressure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('diastole_pressure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='text_process_result_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='text_process_result_pkey')
    )
    op.create_index('ix_text_process_result_id', 'text_process_result', ['id'], unique=False)
    op.drop_index(op.f('ix_runs_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
