"""Renamed TextProcessResult to Run

Revision ID: 83faaee45526
Revises: ff6fa3160a72
Create Date: 2022-04-11 21:33:34.735116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83faaee45526'
down_revision = 'ff6fa3160a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
