"""Added type field to run

Revision ID: 856c6452874d
Revises: 53b70c4d7071
Create Date: 2022-05-09 17:13:42.204502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856c6452874d'
down_revision = '53b70c4d7071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'type')
    # ### end Alembic commands ###
