"""empty message

Revision ID: d3fb01af9c84
Revises: 856c6452874d
Create Date: 2022-05-23 20:33:25.328592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fb01af9c84'
down_revision = '856c6452874d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs_new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_new_id'), 'runs_new', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_new_id'), table_name='runs_new')
    op.drop_table('runs_new')
    # ### end Alembic commands ###
