"""empty message

Revision ID: dc86d77cf16a
Revises: d3fb01af9c84
Create Date: 2022-05-23 21:54:48.878153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc86d77cf16a'
down_revision = 'd3fb01af9c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs_new', sa.Column('type', sa.String(length=30), nullable=True))
    op.add_column('runs_new', sa.Column('finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs_new', 'finished')
    op.drop_column('runs_new', 'type')
    # ### end Alembic commands ###
