"""initial

Revision ID: fa0ae9884768
Revises: 
Create Date: 2022-03-18 23:29:31.476225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0ae9884768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_process_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_corresponding', sa.Boolean(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('systole_pressure', sa.Integer(), nullable=True),
    sa.Column('diastole_pressure', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_process_result_id'), 'text_process_result', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_process_result_id'), table_name='text_process_result')
    op.drop_table('text_process_result')
    # ### end Alembic commands ###
