name: Deploy to server

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        username: ${{ secrets.SERVER_SSH_USERNAME }}
        password: ${{ secrets.SERVER_SSH_PASSWORD }}
        script: |
          cd /usr/src/app
          git pull origin production
          chmod +x ./ci-cd/deploy.sh
          ./ci-cd/deploy.sh
