name: Deploy to server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements/lint.txt
    - name: Lint with flake8 and black
      run: |
        cd backend
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics
        black . --check
  deploy:
    runs-on: ubuntu-latest 
    needs: lint
    steps:
    - name: executing remote ssh deploy commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        username: ${{ secrets.SERVER_SSH_USERNAME }}
        password: ${{ secrets.SERVER_SSH_PASSWORD }}
        script: |
          cd /usr/src/app
          git fetch --all
          git reset --hard origin/master
          
          rm .env
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo DRAMATIQ_BROKER_URL=${{ secrets.DRAMATIQ_BROKER_URL }} >> .env
          echo GF_SERVER_ROOT_URL=${{ secrets.GF_SERVER_ROOT_URL }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo PROMETHEUS_SERVER_ROOT_URL=${{ secrets.PROMETHEUS_SERVER_ROOT_URL }} >> .env
          echo VITE_API_URL=${{ secrets.VITE_API_URL }} >> .env
          echo VITE_ENVIRONMENT=${{ secrets.VITE_ENVIRONMENT }} >> .env
          echo ZINC_FIRST_ADMIN_USER=${{ secrets.ZINC_FIRST_ADMIN_USER }} >> .env
          echo ZINC_FIRST_ADMIN_PASSWORD=${{ secrets.ZINC_FIRST_ADMIN_PASSWORD }} >> .env

          export ZINC_FIRST_ADMIN_USER=${{ secrets.ZINC_FIRST_ADMIN_USER }}
          export ZINC_FIRST_ADMIN_PASSWORD=${{ secrets.ZINC_FIRST_ADMIN_PASSWORD }}
          chmod +x ./ci-cd/deploy.sh
          ./ci-cd/deploy.sh
